export enum LendingStatus {
  // Current Statuses defined in backend
  READER_CREATED_REQUEST,
  OWNER_SUGGESTED_MEETING,
  READER_ACCEPTED_MEETING,
  READER_CONFIRMED_TRANSFER,
  OWNER_CONFIRMED_TRANSFER,
  BORROWED,
  READER_RETURNED_BOOK,
  OWNER_CONFIRMED_RETURNAL,
  OWNER_DENIED,
  READER_WITHDREW
}
